; Projet : Eclairage LED RGB 12V piloté par ESP32
; Carte : ESP32 DevKit générique

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Système de fichiers utilisé pour servir la page web (dossier data/)
board_build.filesystem = littlefs

lib_deps =
	https://github.com/ESP32Async/ESPAsyncWebServer.git
	https://github.com/ESP32Async/AsyncTCP.git
	bblanchon/ArduinoJson @ ^7.0.4
